# Generated by Django 4.2 on 2023-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit_id', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('submit_count', models.IntegerField()),
            ],
        ),
    ]
